"""empty message

Revision ID: 1dfb4a40629c
Revises: b174d9759819
Create Date: 2026-08-19 14:34:48.951513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dfb4a40629c'
down_revision = 'b174d9759819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qualification_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'qualification', ['qualification_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_type', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('qualification_id')

    # ### end Alembic commands ###
