"""Mehrere Tabellen erstellt

Revision ID: 29eedd5d126f
Revises: f6069c938a84
Create Date: 2026-08-12 14:01:54.657288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29eedd5d126f'
down_revision = 'f6069c938a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('zip_code',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('zip_code',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    # ### end Alembic commands ###
