"""test

Revision ID: 33978e0fa579
Revises: 455e61854f2a
Create Date: 2026-08-24 11:16:16.972213

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33978e0fa579'
down_revision = '455e61854f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('shift_type_qualification',
    sa.Column('shift_type_id', sa.Integer(), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualification.id'], ),
    sa.ForeignKeyConstraint(['shift_type_id'], ['shift_type.id'], ),
    sa.PrimaryKeyConstraint('shift_type_id', 'qualification_id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('absence', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.alter_column('company_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=155),
               existing_nullable=False)
        batch_op.alter_column('city',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=155),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('company_name'))
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.alter_column('department_name',
               existing_type=mysql.VARCHAR(length=155),
               nullable=False)

    with op.batch_alter_table('qualification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['id'])

    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.alter_column('shift_start',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               nullable=False)
        batch_op.alter_column('shift_end',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               nullable=False)

    with op.batch_alter_table('shift_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=254),
               nullable=False)
        batch_op.alter_column('start',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               nullable=False)
        batch_op.alter_column('end',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               nullable=False)
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['id'])

    with op.batch_alter_table('user_qualification', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('qualification_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_qualification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.alter_column('qualification_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('shift_type', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('end',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('start',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=254),
               nullable=True)
        batch_op.drop_column('company_id')

    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.alter_column('shift_end',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('shift_start',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('qualification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.alter_column('department_name',
               existing_type=mysql.VARCHAR(length=155),
               nullable=True)

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', mysql.VARCHAR(length=50), nullable=True))
        batch_op.create_index(batch_op.f('company_name'), ['company_name'], unique=True)
        batch_op.alter_column('city',
               existing_type=sa.String(length=155),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=155),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('phone')
        batch_op.drop_column('address')

    with op.batch_alter_table('absence', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    op.drop_table('ticket')
    op.drop_table('shift_type_qualification')
    op.drop_table('invite_code')
    # ### end Alembic commands ###
