"""Schicht Qualifikationen hinzugefügt

Revision ID: bb3a3cf303c7
Revises: 1dfb4a40629c
Create Date: 2026-08-19 15:08:24.062231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb3a3cf303c7'
down_revision = '1dfb4a40629c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_type_qualification',
    sa.Column('shift_type_id', sa.Integer(), nullable=False),
    sa.Column('qualification_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['qualification_id'], ['qualification.id'], ),
    sa.ForeignKeyConstraint(['shift_type_id'], ['shift_type.id'], ),
    sa.PrimaryKeyConstraint('shift_type_id', 'qualification_id')
    )
    with op.batch_alter_table('shift_type', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('shift_type_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('qualification_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qualification_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('shift_type_ibfk_1'), 'qualification', ['qualification_id'], ['id'])

    op.drop_table('shift_type_qualification')
    # ### end Alembic commands ###
